import type { AgentRunDetail, Overview, StockCardIntake } from "../types";

export const stockCardIntakeFixture: StockCardIntake = {
  schema_version: "1.0",
  intake_id: "INT-ABCDEF123456",
  trace_id: "TRACE-INTAKE-ABC123",
  status: "AWAITING_REVIEW",
  provider: "fixture",
  model_name: null,
  gemini_called: false,
  source_filename: "stock_card_scan_demo.png",
  mime_type: "image/png",
  image_sha256: "3".repeat(64),
  image_size_bytes: 245810,
  extraction: {
    schema_version: "1.0",
    facility_name: "Mbale Regional Referral Hospital",
    product_name: "Oxytocin injection 10 IU/ml",
    stock_unit: "Pack of 10 ampoules",
    card_number: "DEMO-OXY-001",
    scenario_date: "2026-08-15",
    store_name: "Main medical store",
    storage_min_c: 2,
    storage_max_c: 8,
    on_hand_packs: 60,
    batch_number: "OXY-MBL-2610A",
    expiry_date: "2026-10-15",
    latest_temperature_c: 5.3,
    redistribution_review: true,
    movements: [
      ["2026-05-01", "Opening", 10],
      ["2026-06-01", "NMS-DEL-6621", 78],
      ["2026-06-30", "HMIS-017-884", 70],
      ["2026-07-31", "HMIS-017-921", 60],
    ].map(([movement_date, reference, balance_packs]) => ({
      movement_date: String(movement_date),
      reference: String(reference),
      batch_number: "OXY-MBL-2610A",
      expiry_date: "2026-10-15",
      received_packs: 0,
      issued_packs: 0,
      balance_packs: Number(balance_packs),
      temperature_c: 5.3,
      remarks: "Synthetic stock movement",
    })),
    evidence: [
      ["facility_name", "Mbale Regional Referral Hospital", 0.99],
      ["product_name", "Oxytocin injection 10 IU/ml", 0.99],
      ["on_hand_packs", "60", 0.99],
      ["batch_number", "OXY-MBL-2610A", 0.98],
      ["expiry_date", "2026-10-15", 0.98],
      ["storage_range", "2–8°C; do not freeze", 0.99],
      ["redistribution_review", "FEFO — review for redistribution", 0.97],
    ].map(([field, quote, confidence]) => ({
      field: String(field),
      quote: String(quote),
      confidence: Number(confidence),
      bbox: [0.1, 0.1, 0.8, 0.2],
    })),
    overall_confidence: 0.98,
  },
  observation: null,
  required_corrections: [],
  security_findings: [],
  corrections: [],
  source_label: "Synthetic demonstration stock card — not current facility data",
  error_code: null,
  created_at: "2026-08-15T10:00:00Z",
  updated_at: "2026-08-15T10:00:00Z",
  accepted_by: null,
  accepted_at: null,
};

stockCardIntakeFixture.observation = {
  facility_id: "F01",
  product_id: "P05",
  batch_id: "BAT-F01-P05-01",
  extraction: stockCardIntakeFixture.extraction,
};

export const agentRunFixture: AgentRunDetail = {
  run: {
    run_id: "RUN-ABCDEF123456",
    workflow: "district_watch_cycle",
    status: "COMPLETED",
    trace_id: "TRACE-AGENT-ABC123",
    requested_by: "facility_worker",
    provider: "fixture",
    model_name: null,
    queue_backend: "local",
    request: {
      schema_version: "1.0",
      recipient_facility_id: "F02",
      product_id: "P05",
      trigger: "demo",
    },
    result_transfer_id: "TR-027",
    event_authors: [
      "stock_intake_agent",
      "watch_agent",
      "match_agent",
      "steward_agent",
      "dispatch_agent",
      "reconciliation_agent",
    ],
    error_code: null,
    created_at: "2026-08-15T11:00:00Z",
    started_at: "2026-08-15T11:00:01Z",
    completed_at: "2026-08-15T11:00:02Z",
  },
  steps: [
    ["stock_intake_agent", "validate_inventory_snapshot", "Validated 70 stock positions"],
    ["watch_agent", "detect_stock_signals", "Detected district needs and safe offers"],
    ["match_agent", "rank_safe_transfers", "Found 11 safe packs nearby"],
    ["steward_agent", "evaluate_governance", "All safety gates passed"],
    ["dispatch_agent", "check_dispatch_gate", "Waiting for the District Health Officer"],
    ["reconciliation_agent", "check_reconciliation_gate", "No signed receipt is ready"],
  ].map(([agent_name, tool_name, summary], index) => ({
    step_id: `STEP-ABCDEF12345${index}`,
    run_id: "RUN-ABCDEF123456",
    sequence: index + 1,
    agent_name,
    tool_name,
    status: index < 4 ? "COMPLETED" as const : "WAITING" as const,
    summary,
    evidence: {},
    started_at: "2026-08-15T11:00:01Z",
    completed_at: "2026-08-15T11:00:02Z",
  })),
};

export const overviewFixture: Overview = {
  synthetic_data: true,
  scenario_date: "2026-08-15",
  protocol: {
    note: null,
    latest_reconciliation: null,
    mutation_count: 0,
    quarantined_count: 0,
  },
  governance: {
    audit_chain: {
      verified: true,
      event_count: 1,
      last_sequence: 1,
      head_hash: "a".repeat(64),
      verified_at: "2026-08-15T11:00:00Z",
    },
    unresolved_exceptions: 0,
    exceptions: [],
    authorization_mode: "fixture-role-headers",
    role_permissions: {
      facility_worker: ["record_stock", "reconcile_receipt"],
      dho_approver: ["approve_transfer", "resolve_exception"],
      auditor: ["read_audit"],
    },
    request_id: "REQ-TEST0001",
    reasoning_policy: "concise-decision-evidence-only",
  },
  agent_run: null,
  stock_card_intake: null,
  recommendation: {
    schema_version: "1.0",
    transfer_id: "TR-027",
    donor_facility_id: "F01",
    donor_name: "Mbale Regional Referral Hospital",
    donor_short_name: "Mbale RRH",
    recipient_facility_id: "F02",
    recipient_name: "Busiu Health Centre IV",
    recipient_short_name: "Busiu HC IV",
    product_id: "P05",
    product_name: "Oxytocin 10 IU/ml",
    batch_id: "BAT-F01-P05-01",
    batch_number: "OXY-MBL-2610A",
    quantity: 11,
    transfer_unit: "pack",
    route_id: "R-COLD-01",
    vehicle_id: "VEH-COLD-01",
    approval_id: "APR-DHO-001",
    score: 51.2,
    status: "FOUND",
    source_label: "Synthetic demonstration data — not current facility stock",
    evidence: {
      donor_on_hand: 60,
      donor_monthly_use: 12,
      donor_cover_before_days: 150,
      donor_cover_after_days: 122,
      recipient_on_hand: 1,
      recipient_monthly_use: 6,
      recipient_cover_before_days: 5,
      recipient_cover_after_days: 60,
      route_km: 21.7,
      route_minutes: 37,
      expiry_date: "2026-10-15",
      projected_expiry_risk_avoided: 11,
      score_components: { need: 44, expiry: 9.92, distance: -2.72 },
    },
    policy: {
      allowed: true,
      human_approval_required: true,
      checks: { donor_cover: true, recipient_level: true, batch_quality: true, route: true, transport: true },
      reasons: [
        "Donor retains 12 packs of protected safety stock",
        "Receiving facility is authorized for this medicine",
        "Available batch OXY-MBL-2610A selected by earliest expiry",
        "A viable district route is available",
        "Temperature and carrying capacity are compatible",
        "Named DHO approval required",
      ],
    },
    metrics: {
      transfer_id: "TR-027",
      recipient_cover_restored_days: 55,
      donor_cover_retained_days: 122,
      projected_expiry_risk_avoided: 11,
      distance_km: 21.7,
    },
  },
  activity: [
    {
      event_id: "EVT-001",
      sequence: 1,
      occurred_at: "2026-08-15T11:00:00Z",
      trace_id: "TRACE-SEED",
      actor_id: "fixture-importer",
      event_type: "FIXTURE_SEEDED",
      summary: "Validated synthetic fixture state loaded",
      event_hash: "a".repeat(64),
      details: {},
    },
  ],
  network: [
    {
      facility_id: "F01",
      facility_name: "Mbale Regional Referral Hospital",
      facility_short_name: "Mbale RRH",
      product_id: "P05",
      product_name: "Oxytocin 10 IU/ml",
      on_hand: 60,
      monthly_use: 12,
      days_of_cover: 150,
      target_quantity: 24,
      safety_quantity: 12,
      need_quantity: 0,
      safe_release_quantity: 48,
      state: "safe_surplus",
    },
    {
      facility_id: "F02",
      facility_name: "Busiu Health Centre IV",
      facility_short_name: "Busiu HC IV",
      product_id: "P05",
      product_name: "Oxytocin 10 IU/ml",
      on_hand: 1,
      monthly_use: 6,
      days_of_cover: 5,
      target_quantity: 12,
      safety_quantity: 6,
      need_quantity: 11,
      safe_release_quantity: 0,
      state: "needs_stock",
    },
  ],
};
