import type { AgentRunDetail, Overview } from "../types";

export const agentRunFixture: AgentRunDetail = {
  run: {
    run_id: "RUN-ABCDEF123456",
    workflow: "district_watch_cycle",
    status: "COMPLETED",
    trace_id: "TRACE-AGENT-ABC123",
    requested_by: "facility_worker",
    provider: "fixture",
    model_name: null,
    queue_backend: "local",
    request: {
      schema_version: "1.0",
      recipient_facility_id: "F02",
      product_id: "P05",
      trigger: "demo",
    },
    result_transfer_id: "TR-027",
    event_authors: [
      "stock_intake_agent",
      "watch_agent",
      "match_agent",
      "steward_agent",
      "dispatch_agent",
      "reconciliation_agent",
    ],
    error_code: null,
    created_at: "2026-08-15T11:00:00Z",
    started_at: "2026-08-15T11:00:01Z",
    completed_at: "2026-08-15T11:00:02Z",
  },
  steps: [
    ["stock_intake_agent", "validate_inventory_snapshot", "Validated 70 stock positions"],
    ["watch_agent", "detect_stock_signals", "Detected district needs and safe offers"],
    ["match_agent", "rank_safe_transfers", "Found 11 safe packs nearby"],
    ["steward_agent", "evaluate_governance", "All safety gates passed"],
    ["dispatch_agent", "check_dispatch_gate", "Waiting for the District Health Officer"],
    ["reconciliation_agent", "check_reconciliation_gate", "No signed receipt is ready"],
  ].map(([agent_name, tool_name, summary], index) => ({
    step_id: `STEP-ABCDEF12345${index}`,
    run_id: "RUN-ABCDEF123456",
    sequence: index + 1,
    agent_name,
    tool_name,
    status: index < 4 ? "COMPLETED" as const : "WAITING" as const,
    summary,
    evidence: {},
    started_at: "2026-08-15T11:00:01Z",
    completed_at: "2026-08-15T11:00:02Z",
  })),
};

export const overviewFixture: Overview = {
  synthetic_data: true,
  scenario_date: "2026-08-15",
  agent_run: null,
  recommendation: {
    schema_version: "1.0",
    transfer_id: "TR-027",
    donor_facility_id: "F01",
    donor_name: "Mbale Regional Referral Hospital",
    donor_short_name: "Mbale RRH",
    recipient_facility_id: "F02",
    recipient_name: "Busiu Health Centre IV",
    recipient_short_name: "Busiu HC IV",
    product_id: "P05",
    product_name: "Oxytocin 10 IU/ml",
    batch_id: "BAT-F01-P05-01",
    batch_number: "OXY-MBL-2610A",
    quantity: 11,
    transfer_unit: "pack",
    route_id: "R-COLD-01",
    vehicle_id: "VEH-COLD-01",
    approval_id: "APR-DHO-001",
    score: 51.2,
    status: "FOUND",
    source_label: "Synthetic demonstration data — not current facility stock",
    evidence: {
      donor_on_hand: 60,
      donor_monthly_use: 12,
      donor_cover_before_days: 150,
      donor_cover_after_days: 122,
      recipient_on_hand: 1,
      recipient_monthly_use: 6,
      recipient_cover_before_days: 5,
      recipient_cover_after_days: 60,
      route_km: 21.7,
      route_minutes: 37,
      expiry_date: "2026-10-15",
      projected_expiry_risk_avoided: 11,
      score_components: { need: 44, expiry: 9.92, distance: -2.72 },
    },
    policy: {
      allowed: true,
      human_approval_required: true,
      checks: { donor_cover: true, recipient_level: true, batch_quality: true, route: true, transport: true },
      reasons: [
        "Donor retains 12 packs of protected safety stock",
        "Receiving facility is authorized for this medicine",
        "Available batch OXY-MBL-2610A selected by earliest expiry",
        "A viable district route is available",
        "Temperature and carrying capacity are compatible",
        "Named DHO approval required",
      ],
    },
    metrics: {
      transfer_id: "TR-027",
      recipient_cover_restored_days: 55,
      donor_cover_retained_days: 122,
      projected_expiry_risk_avoided: 11,
      distance_km: 21.7,
    },
  },
  activity: [
    {
      event_id: "EVT-001",
      sequence: 1,
      occurred_at: "2026-08-15T11:00:00Z",
      trace_id: "TRACE-SEED",
      actor_id: "fixture-importer",
      event_type: "FIXTURE_SEEDED",
      summary: "Validated synthetic fixture state loaded",
      event_hash: "a".repeat(64),
      details: {},
    },
  ],
  network: [
    {
      facility_id: "F01",
      facility_name: "Mbale Regional Referral Hospital",
      facility_short_name: "Mbale RRH",
      product_id: "P05",
      product_name: "Oxytocin 10 IU/ml",
      on_hand: 60,
      monthly_use: 12,
      days_of_cover: 150,
      target_quantity: 24,
      safety_quantity: 12,
      need_quantity: 0,
      safe_release_quantity: 48,
      state: "safe_surplus",
    },
    {
      facility_id: "F02",
      facility_name: "Busiu Health Centre IV",
      facility_short_name: "Busiu HC IV",
      product_id: "P05",
      product_name: "Oxytocin 10 IU/ml",
      on_hand: 1,
      monthly_use: 6,
      days_of_cover: 5,
      target_quantity: 12,
      safety_quantity: 6,
      need_quantity: 11,
      safe_release_quantity: 0,
      state: "needs_stock",
    },
  ],
};
